# Generated by Django 2.1.7 on 2019-05-26 01:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190518_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', verbose_name='テキスト'),
        ),
    ]
