# Generated by Django 2.1.7 on 2019-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumnail', verbose_name='サムネイル（空欄可）'),
        ),
    ]
