# Generated by Django 2.2.5 on 2020-09-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190528_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_publick',
            field=models.BooleanField(choices=[(True, '公開'), (False, '非公開')], default=True, verbose_name='選択'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
