# Generated by Django 2.2.5 on 2021-03-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200904_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'ブログリスト', 'verbose_name_plural': 'ブログリスト'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'ブログカテゴリーリスト', 'verbose_name_plural': 'ブログカテゴリーリスト'},
        ),
    ]
