# Generated by Django 2.2.5 on 2023-08-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210327_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='人気記事')),
                ('path', models.CharField(max_length=100, verbose_name='URL')),
                ('view', models.IntegerField(verbose_name='閲覧数')),
            ],
            options={
                'verbose_name': '人気記事リスト',
                'verbose_name_plural': '人気記事リスト',
            },
        ),
    ]
